/*=====================================================================
TestUtils.cpp
-------------
File created by ClassTemplate on Wed Jul 18 14:25:06 2007
Code By Nicholas Chapman.
=====================================================================*/
#include "TestUtils.h"


#include "../maths/mathstypes.h"
#include "../utils/StringUtils.h"
#include "../utils/PlatformUtils.h"
#include "../utils/prebuild_repos_info.h"
#include "../utils/ConPrint.h"
#include <stdlib.h>
#include <assert.h>


namespace TestUtils
{


void doTestStringsEqual(const std::string& a, const std::string& b, const char* a_str, const char* b_str, long line, const char* file)
{
	if(a != b)
	{
		printMessageAndFail("Test equal failed: " + std::string(file) + ", line " + toString((int)line) + ":\n" +
			a_str + "='" + a + "' was not equal to " + b_str + "='" + b + "'");
	}
}


void doTestAssert(bool expr, const char* test, long line, const char* file)
{
	if(!expr)
	{
		printMessageAndFail("Test assertion failed: " + std::string(file) + ", line " + toString((int)line) + ":\n" + std::string(test));
	}
}


void doFailTest(const std::string& msg, long line, const char* file)
{
	printMessageAndFail("Test failed: " + std::string(file) + ", line " + toString((int)line) + ":\n" + msg);
}


void printMessageAndFail(const std::string& msg)
{
	conPrint(msg);
	assert(0);
	exit(1);
}


const std::string getIndigoTestReposDir()
{
	// Is now generated by prebuild.rb and stored in prebuild_repos_info.h.
	return test_repos_dir;
}


void silentPrint(const std::string& s)
{
	if(PlatformUtils::getProcessID() == 0)
		conPrint(s);
}


} // end namespace TestUtils
