//
// Generated by makeclass.rb on Sat Feb 13 21:34:45 +1300 2010.
// Copyright Nicholas Chapman.
//
#include "ParallelFor.h"


ParallelFor::ParallelFor()
{}


ParallelFor::~ParallelFor()
{}


